defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: wufoo_clone_development

test:
  <<: *defaults
  database: wufoo_clone_test

# set these environment variables on your prod server
production:
    uri: <%= ENV['MONGOHQ_URL'] %>
